### ISSUE TITLE
Support stable 1.36

### ISSUE THREAD

**Issue by Nemo157** [rustasync/runtime#68]
I haven't verified fully whether this is possible, but it seems like adding support for `fn main() -> impl Future` (and similar for test functions) would allow using `runtime` on current stable.

Minimal example I would expect to work:

```rust
// runtime = { git = "https://github.com/rustasync/runtime" }
// futures-preview = "0.3.0-alpha.17"

use futures::future;

#[runtime::main]
fn main() -> impl Future<Output = ()> {
    println!("Hello, world!");
    future::ready(())
}
```

**Comment by yoshuawuyts** [comment]
@Nemo157 that would be very cool! I suspect with a bit of effort we could lift the return type, remove the arrow and insert it as `Output = #ret`. 

That said, I do think we should keep the nightly constraint until async_await is on stable. Mostly because e.g. introducing fs free functions will likely have to be `async fn`. But those aren't here yet (:
