### ISSUE TITLE
Please document compatibility with high-level networking and web frameworks

### ISSUE THREAD

**Issue by igor-petruk** [rustasync/runtime#79]
Please extend README of the current compatibly status with higher level frameworks, such as hyper, actix-web, etc. Please disambiguate if it is transparent to them, if Tokio Runtime must be used or neither of those and it is not compatible at all at the moment.

This library is very convenient to use in simple examples, but it would very nice for newcomers to know if this can be a foundation to their web apps today or in planned future milestone

**Comment by danieleades** [comment]
i wonder where the burden of documentation lies?

Hyper is currently implicitly dependent on the tokio runtime. Most of the high-level frameworks depend either directly or transitively on Hyper (it's more or less the defacto standard) and therefore require the tokio runtime.

To be honest i think that it's on these frameworks to document the limitation, and to commit to removing this dependency in future.

see https://github.com/hyperium/hyper/issues/1613

**Comment by igor-petruk** [comment]
This is just an idea to improve convenience of the users. I did not mean some large documentation, but a paragraph roughly explaining what you explained here. A simple paragraph is a good alternative to waiting for indefinite amount of time for the proper documentation the frameworks side. Each framework can document their compatibility with runtime. But runtime is a cross-product, so it may be in a good position to outline its place in ecosystem, how does it relate to other components

**Comment by danieleades** [comment]
just to keep you updated-
The implicit dependence on a particular runtime comes from any library that 'spawns' futures. Not many do, but Hyper is one that does. Hyper does allow you to use your own custom executor instead of the tokio executor, and it does this by exposing a generic executor trait. Hyper provides tokio as a default runtime as a default feature, unless explicitly disabled.

There is currently no consistent way to do this across the ecosystem, which is a bit of a gap. Perhaps the futures crate should provide a Spawn/Executor trait? Perhaps Hyper should not provide an executor at all by default, and use tokio executor as an opt-in feature.

Some libraries expose Hyper's custom runtime feature, and the ones that don't could add it without too much difficulty. So again I suggest jumping up and down at that end. I suspect there's a similar amount of effort in adding the ability to use custom runtimes as there is in investigating and documenting which ones cannot support it.
